### ISSUE TITLE
Type-safe forms

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/hyper#19]
**Goals:**

* Rendering forms for POST resources with `application/www-form-urlencoded` content type should be type-safe
  - All fields present
  - Correct input types for fields
* Rendered forms should be customizable/extendable in some way, so that the user can add help texts, class attributes, etc

**Notes:**

The current working design does not enforce type-safety, it merely gives you all the input fields with correct types to assemble your form with. Thus, you could override the `type` attribute, omit certain fields, etc. I'm not sure if it is feasible to enforce it without having some type-level Set construct. Anyway, the first attempts will do this less safe approach, and then we can iterate.

The idea is to represent forms as such:

```purescript
type PersonForm =
  InputHidden "id" Int
  :<> InputText "name"
  :<> InputNumber "age"
```

And then in rendering, do something like:

```purescript
instance encodeHTMLNewPerson :: EncodeHTML NewPerson where
  encodeHTML _ =
    case toForms site of
      -- this requires a `ReqBody FormUrlEncoded PersonForm` in the corr routing type
      _ :<|> _ :<|> savePersonForm :<|> _ →
        savePersonForm renderForm
  where
    renderForm (idField :<> nameField :<> ageField) = do
      idField -- automatically type=hidden
      label "Age"
      nameField
      label "Age"
      ageField -- automatically type=number
```

And have the rendered fields automatically enclosed in a correct `<form>` with `action` and `method` attributes.

Branch: https://github.com/owickstrom/hyper/tree/type-safe-forms

**TODO:**

- [x] (Basic) type-level representation of forms
- [ ] FromFormData/ToFormData type classes
- [ ] Generate extendable markup for forms
- [ ] `ReqBody ct t` for reading, parsing, and passing form data to handlers

**Comment by kritzcreek** [comment]
Not sure if you drew your inspiration from it, but Haskell's `digestive-functors` library sounds like the thing you want to build. Maybe you can get some intuitions/ideas from it.

https://hackage.haskell.org/package/digestive-functors

**Comment by owickstrom** [comment]
@kRITZCREEK thanks for the link, it looks useful!

**Comment by owickstrom** [comment]
@kRITZCREEK this is running now, with some issues still left to fix: https://gist.github.com/owickstrom/2281f69c1ec979803415177120e8f666#file-safeform-purs-L67-L79

Not sure if an API more like `digestive-functors` would be better, or if it would fit with Hyper and the type-level routing. The nice thing with the current design is that the form fields are derived from the actual routed form, not something that is in scope but is possibly not used.

Any thoughts? :)

**Comment by owickstrom** [comment]
Also, would rather have `renderForm (idField :<> nameField :<> ageField) = ...` be a function with multiple arguments, i.e. `renderForm idField nameField ageField = ...`. Then you would get warning if you forget to include any field in your markup.

**Comment by owickstrom** [comment]
This will most likely be a separate library if realized, so closing this.
